"""
Central config: file paths and constants shared across the backend package.
All paths are relative to DATA_DIR - copy the artifact files generated by
notebooks/GridHeat_AI_Pipeline_Texas.ipynb into this folder before running
the frontend or the tests that hit real data.

Secrets (FORTYGUARD_API_KEY, GROQ_API_KEY, LANGCHAIN_API_KEY, EIA_API_KEY)
are read from the environment. Locally, put them in a .env file at the repo
root (see .env.example) - this module loads it automatically via
python-dotenv. On Streamlit Community Cloud, set them instead in the app's
Secrets UI (.streamlit/secrets.toml locally maps to the same st.secrets
there); either way they end up in os.environ by the time this module is
imported.

Pilot: Harris County, TX (Houston) - selected in notebook Section 2 as the
top-ranked candidate county (heat + EAGLE-I outage history + EJScreen
vulnerability), see notebooks/GridHeat_AI_Pipeline_Texas.ipynb Section 2.
"""
import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"

load_dotenv(BASE_DIR / ".env")

# ---- Pilot area ----
PILOT_COUNTY = "Harris"          # Harris County, TX (Houston) - see notebook Section 2
PILOT_CRS = "EPSG:3083"          # Texas Centric Albers Equal Area (was EPSG:3310 for Fresno/CA)

# ---- Secrets (from environment / .env - never hardcode real keys here) ----
FORTYGUARD_API_KEY = os.environ.get("FORTYGUARD_API_KEY", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
LANGCHAIN_API_KEY = os.environ.get("LANGCHAIN_API_KEY", "")  # optional - LangSmith tracing, see backend/graph.py
EIA_API_KEY = os.environ.get("EIA_API_KEY", "")              # optional - live prev-day ERCOT demand feature

# ---- Static artifacts (generated once by the notebook's data pipeline) ----
PILOT_AOI_PATH = DATA_DIR / "harris_aoi_precise.geojson"
HEAT_ZONE_GRID_PATH = DATA_DIR / "heat_zone_grid_tx.geojson"
SUBSTATIONS_PATH = DATA_DIR / "tx_substations_clean.geojson"
TRANSMISSION_LINES_PATH = DATA_DIR / "tx_transmission_lines_clean.geojson"
EJSCREEN_PATH = DATA_DIR / "ejscreen_tx_clean.geojson"
BATTERY_STORAGE_PATH = DATA_DIR / "battery_storage_tx_clean.geojson"

LINES_JOINED_PATH = DATA_DIR / "lines_joined_tx.csv"
VULNERABILITY_JOINED_PATH = DATA_DIR / "vulnerability_joined_tx.csv"
BATTERY_JOINED_PATH = DATA_DIR / "battery_joined_tx.csv"
INFRA_WEIGHTS_PATH = DATA_DIR / "infra_weights_tx.csv"

EAGLE_I_OUTAGES_PATH = DATA_DIR / "eagle_i_tx_clean.csv"
COUNTY_SCOREBOARD_PATH = DATA_DIR / "tx_county_scoreboard.csv"  # Section 2 Stage B candidate-county scoreboard

ERCOT_DEMAND_CLEAN_PATH = DATA_DIR / "ercot_demand_clean.csv"
TEMP_DEMAND_MERGED_PATH = DATA_DIR / "tx_temp_demand_merged.csv"
DEMAND_MODEL_PATH = DATA_DIR / "tx_demand_model.joblib"  # bundle: {"linear","multivariate","features"}

# ---- Live/generated-per-run artifacts ----
LIVE_HEAT_PATH = DATA_DIR / "tx_live_heat_by_zone.csv"
RISK_TABLE_PATH = DATA_DIR / "tx_risk_table.csv"

# ---- Risk engine ----
RISK_WEIGHTS = {"heat": 0.30, "demand": 0.25, "infrastructure": 0.20, "outage": 0.15, "vulnerability": 0.10}
DEFAULT_RISK_THRESHOLD = 40.0  # placeholder carried over from the Fresno run - recalibrate once real Texas scores are in, see notebook Section 7

# ---- Optimization ----
# Scenario assumptions used to demonstrate constrained optimization - NOT
# utility-specific cost estimates or empirically calibrated intervention
# effects. Unchanged from the California version (no state-specific logic
# here to begin with).
ACTIONS = {
    "battery_dispatch":     {"cost": 20_000, "risk_reduction_pct": 30, "requires_battery": True},
    "crew_deployment":      {"cost": 8_000,  "risk_reduction_pct": 12, "requires_battery": False},
    "demand_response":      {"cost": 5_000,  "risk_reduction_pct": 18, "requires_battery": False},
    "emergency_monitoring": {"cost": 3_000,  "risk_reduction_pct": 5,  "requires_battery": False},
}

# ---- LLM explanation layer ----
EXPLANATION_MODEL = "openai/gpt-oss-120b"  # Groq free-tier
